apiVersion: v1
kind: Secret
metadata:
  name: order-service-secrets
  namespace: kumar-order-service
type: Opaque

stringData:
  SPRING_DATASOURCE_USERNAME: postgres
  SPRING_DATASOURCE_PASSWORD: "MainPassword1%"