apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: kumar-order-service
  labels:
    app: order-service
    tier: backend
spec:
  #type: LoadBalancer
  selector:
    app: order-service
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: kumar-order-service
  labels:
    app: order-service
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
        tier: backend
    spec:
      containers:
      - name: order-service
        image: ssadcloud/order-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        envFrom:
        - configMapRef:
            name: order-service-config
        - secretRef:
            name: order-service-secrets