apiVersion: apps/v1
kind: Deployment
metadata:
  name: kkm03-deployment
  labels:
    app: kkm03-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kkm03-app
  template:
    metadata:
      labels:
        app: kkm03-app
    spec:
      containers:
      - name: kkm03-app-container
        image: 792172459577.dkr.ecr.us-east-1.amazonaws.com/mkk03_ecr:latest
        ports:
        - containerPort: 5000