apiVersion: apps/v1
kind: Deployment
metadata:
  name: KK-deployment
  labels:
    app: KK-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: KK-app
  template:
    metadata:
      labels:
        app: KK-app
    spec:
      containers:
      - name: KK-app-container
        image: 792172459577.dkr.ecr.us-east-1.amazonaws.com/mkk03_ecr:latest
        ports:
        - containerPort: 5000