apiVersion: v1
kind: Service
metadata:
  name: kkm03-service
  labels:
    app: kkm03-app
spec:
  type: LoadBalancer
  selector:
    app: kkm03-app
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      protocol: TCP