apiVersion: v1
kind: Service
metadata:
  name: kumar-service
  labels:
    app: kumar-app
spec:
  type: LoadBalancer
  selector:
    app: kumar-app
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      protocol: TCP