apiVersion: v1
kind: Service
metadata:
  name: KK-service
  labels:
    app: KK-app
spec:
  type: LoadBalancer
  selector:
    app: KK-app
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      protocol: TCP